image: python:3.7.4-alpine3.10

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - docker build -t apilib .
          - docker run -t apilib pytest
          - docker run -t apilib /bin/bash -c "coverage run --source=. -m pytest . &&  coverage report"