image: python:3.7.4-alpine3.10

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - docker build -t import .
          - docker run -t import pytest
          - docker run -t import /bin/bash -c "coverage run --source=. -m pytest . &&  coverage report"