image: python:3.7.4-alpine3.10

pipelines:
  default:
    - step:
        name: Build
        services:
          - docker
        image: atlassian/pipelines-awscli
        script: 
          - aws ecr get-login --no-include-email --region eu-west-1 > login.sh
          - sh login.sh
          - TAG=${BITBUCKET_COMMIT}
          - AWS_REGISTRY_URL=467586146532.dkr.ecr.eu-west-1.amazonaws.com
          - export VALSYS_API_BUILD=test
          - docker build -t $AWS_REGISTRY_URL/vslib:$TAG .
          - docker push $AWS_REGISTRY_URL/vslib:$TAG

    - step:
        name: Unit tests
        services:
          - docker
        image: atlassian/pipelines-awscli
        script:
          - aws ecr get-login --no-include-email --region eu-west-1 > login.sh
          - sh login.sh
          - TAG=${BITBUCKET_COMMIT}
          - AWS_REGISTRY_URL=467586146532.dkr.ecr.eu-west-1.amazonaws.com
          - docker run -t $AWS_REGISTRY_URL/vslib:$TAG make test
          - docker run -t $AWS_REGISTRY_URL/vslib:$TAG /bin/bash -c "make coverage-ci"

    - step:
        name: Integration tests
        services:
          - docker
        script:
          - export VALSYS_API_BUILD=test
          - docker build -t apilib .
          - docker run -t apilib /bin/bash -c "make inttest"