
FROM python:3.8.9 
ADD . /valsys
WORKDIR /valsys

#ARG VALSYS_API_SOCKET
#ENV VALSYS_API_SOCKET=$VALSYS_API_SOCKET

#ARG VALSYS_API_SERVER
#ENV VALSYS_API_SERVER=$VALSYS_API_SERVER

#ARG VALSYS_API_USER
#ENV VALSYS_API_USER=$VALSYS_API_USER

#ARG VALSYS_API_PASSWORD
#ENV VALSYS_API_PASSWORD=$VALSYS_API_PASSWORD

RUN pip install -r requirements.txt
