site_name: Valsys

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            heading_level: 5
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      toc_depth: 4
