BASE_SCK = "ws://localhost:5100"
BASE_URL = "http://localhost:5200"

SCK_MODELING_CREATE = f"{BASE_SCK}/modeling/create/"
URL_LOGIN_USERS = f"{BASE_URL}/users/login"
URL_CONFIGS = f"{BASE_URL}/uploader/configuration"
URL_TEMPLATES = f"{BASE_URL}/users/model-templates"
URL_MODELING_MODEL_PROPERTIES = f"{BASE_URL}/modeling/model-properties"
URL_MODEL_INFO = f"{BASE_URL}/modeling/model-information"
URL_RECALC_MODEL = f"{BASE_URL}/modeling/recalculate"
URL_CASE = f"{BASE_URL}/modeling/case"
URL_DELETE_MODULE = f"{BASE_URL}/modeling/delete-module"
URL_ADD_MODULE = f"{BASE_URL}/modeling/add-module"
URL_ADD_ITEM = f"{BASE_URL}/modeling/add-item"
URL_EDIT_FORMAT = f"{BASE_URL}/modeling/edit-format"
URL_EDIT_FORMULA = f"{BASE_URL}/modeling/edit-formula"
URL_USERS_SHARE_MODEL = f"{BASE_URL}/users/share-model"
URL_USERS_MODELS = f"{BASE_URL}/users/models"


API_USERNAME = "jonathan.pearson@valsys.io"
API_PASSWORD = "Solaris30"
