name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       docker build -t apilib .
       docker run -t apilib make test
       docker run -t apilib /bin/bash -c "make coverage-ci"
        